Fixed invalid tupDesc for fdw dummy motion receiver
Fdw motion receive cannot directly use tupDesc because the sender is
from another cluster, we should set it to fdw scan node. Otherwise it
reports:

ERROR:  attribute number 1 exceeds number of columns 0 (execQual.c:739)  (seg0 slice1 10.34.49.127:25435 pid=62475) (execQual.c:739)